export const CHAT_USER = "CHAT_USER";
export const ACTIVE_USER = "ACTIVE_USER";
export const FULL_USER = "FULL_USER";
export const ADD_LOGGED_USER = "ADD_LOGGED_USER";
export const CREATE_GROUP = "CREATE_GROUP";
export const REQUEST_CHAT = "REQUEST_CHAT";
export const REQUEST_SUCESS = "REQUEST_SUCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const SET_IMAGE = "SET_IMAGE";
export const SET_AUDIO = "SET_AUDIO";
export const SET_FILE = "SET_FILE";
export const REQUEST_CONTACTS = "REQUEST_CONTACTS";
export const CONTACTS_SUCESS = "CONTACTS_SUCESS";
export const DELETE_READ = "DELETE_READ";
export const SETMESSAGEREPLY = "SETMESSAGEREPLY";
export const CLEARMESSAGEREPLY = "CLEARMESSAGEREPLY";








